# Generated by Django 5.0.6 on 2024-07-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acesorios',
            new_name='Accesorios',
        ),
    ]
