# Generated by Django 5.0.6 on 2024-07-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_acesorios_accesorios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorios',
            old_name='tipo',
            new_name='nombre',
        ),
    ]
