# Generated by Django 5.0.6 on 2024-07-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_rename_tipo_accesorios_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peluqueros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Clientes',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='turno',
            new_name='nombre_mascota',
        ),
    ]
